name: Bot Workflow

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl lxml pytz telebot python-docx matplotlib fuzzywuzzy

    - name: Start Timer Workflow
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $PAT_TOKEN" \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/timer_workflow.yml/dispatches \
             -d '{"ref":"main"}'

    - name: Run Bot Script
      run: |
          python bot_test.py &
          echo "Waiting for 18000 seconds..."
          sleep 18000
          echo "Stopping the workflow..."
          exit 0
